<h1>Recover Password</h1>

<p>Please enter your new password.</p>
<form name="recover-password-token" method="post">
<table width="450px">
</tr>
<tr>
 <td valign="top">
  <label for="password">password</label>
 </td>
 <td valign="top">
  <input  type="password" name="password" maxlength="50" size="30">
 </td>
</tr>

</tr>
<tr>
 <td colspan="2" style="text-align:center">
  <input type="submit" value="Submit">
 </td>
</tr>
</table>
</form>
