<h1>Recover Password</h1>

<p>Please enter your username or email, and a password change link will be sent to you.</p>
<form name="recover-password-token" method="post">
<table width="450px">
</tr>
<tr>
 <td valign="top">
  <label for="username">username</label>
 </td>
 <td valign="top">
  <input  type="text" name="username" maxlength="50" size="30">
 </td>
</tr>

<tr>
 <td valign="top"">
  <label for="email">email</label>
 </td>
 <td valign="top">
  <input  type="text" name="email" maxlength="50" size="30">
 </td>
</tr>

</tr>
<tr>
 <td colspan="2" style="text-align:center">
  <input type="submit" value="Submit">
 </td>
</tr>
</table>
</form>